/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();

    }

    @Test public void testResturanttoString(){
        Resturant resturant= new Resturant();
        resturant.toString()
    }
}
