/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyFirstPro;

public class App {
    
    int age = 22;
    double height = 170.5;
    float weight;
    byte order;
    long longValue;
    short hortValue;

    boolean isTested = true;

    String name = "Hello World!";
    char letter = 'c';   // '1'  '$' ...

    public int getAge(){
        return 5;
    }

    public void printCharacter(char c){
        // ......
        return;
    }


    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int var = 0;
        int ages[] = new int[10];     // provide the size
        System.out.println(new App().getGreeting());
        System.out.println(var);
        ages[0]= 3;
    }
}
