/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;
import org.checkerframework.checker.units.qual.C;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Contact contact = new Contact("FirsName","LastName",20);
        Contact contact1 = new Contact("FirsName1","LastName1",20);
        Contact contact2 = new Contact("FirsName2","LastName2",20);
        List<Contact> contacts = new ArrayList<Contact>();
        contacts.add(contact);
        contacts.add(contact1);
        contacts.add(contact2);
        Gson gson = new Gson();
        String contactJson = gson.toJson(contacts);
//        String contactJson = "{\"firstName\": \"John\",\n" +
//                "    \"lastName\": \"Smith\",\n" +
//                "    \"age\": 25,\n" +
//                "    \"address\": {\n" +
//                "        \"streetAddress\": \"21 2nd Street\",\n" +
//                "        \"city\": \"New York\",\n" +
//                "        \"state\": \"NY\",\n" +
//                "        \"postalCode\": 10021\n" +
//                "    }}";
      //  Contact contact = gson.fromJson(contactJson, Contact.class);
        System.out.println(contactJson);
    }
}
