/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LinkedList ll = new LinkedList();
        ll.add(5);
        ll.add(1);
        ll.insert(4);

        Node current = ll.head;

        while(current != null){
            System.out.println(current.value);
            current = current.next;
        }
    }
}
