/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testReverseArray(){
        // 4 5 6 7 8
        // 8 7 6 5 4
        int[] originalArr1 = {4,5,6,7,8};
        int[] reversedArray1 = {8,7,6,5,4};
        assertEquals("This method is supposed to reverse an array", Arrays.toString(reversedArray1),Arrays.toString(App.reverseArray(originalArr1)));

        // 0 1 2
        // 2 1 0
        int[] originalArr2 = {0,1,2};
        int[] reversedArray2 = {2,1,0};
        assertEquals("This method is supposed to reverse an array", Arrays.toString(reversedArray2),Arrays.toString(App.reverseArray(originalArr2)));
        //
        //
        int[] originalArr3 = {};
        int[] reversedArray3 = {};
        assertEquals("This method is supposed to reverse an array", Arrays.toString(reversedArray3),Arrays.toString(App.reverseArray(originalArr3)));
    }
}
