/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.checkerframework.checker.units.qual.A;
import otherPackage.ChildInDifferentPackage;

public class App {

    public static void main(String[] args) {
        // Creating an instance of the parent class ..
        ParentClass parentClass = new ParentClass();
        System.out.println(parentClass);  // toString

        // I have direct access to public fields from anywhere inside the project
        //System.out.println(parentClass.publicIntInsideParent);
        // I have direct access to protected fields only if I am in the same package
        //System.out.println(parentClass.protectedIntInsideParent);
        // I have no access to private methods or fields in any other class
        //System.out.println(parentClass.privateIntInsideParent);

        // Creating an instance of the first child class
//        FirstChild firstChild = new FirstChild();
//        firstChild.printHello();

        // Creating an instance of the second child
//        AnotherChild anotherChild = new AnotherChild();
//        anotherChild.printHello();

        // Creating an instance of a child class in another package
//        ChildInDifferentPackage childInDifferentPackage = new ChildInDifferentPackage();
//        childInDifferentPackage.printHello();

//        GrandChild grandChild = new GrandChild();
//        grandChild.mehotdExistsOnlyInFirstChild();

    }
}
